-- Only the rows this migration inserted. An item pointing at one of these units will
-- hold the delete back (items.unit_id is ON DELETE RESTRICT), which is the correct
-- outcome: reverting the seed must not silently strip units off people's lists.

DELETE FROM units WHERE name IN (
    "unit",
    "pair",
    "dozen",
    "pack",
    "box",
    "bag",
    "bottle",
    "can",
    "jar",
    "tin",
    "tube",
    "sachet",
    "roll",
    "bunch",
    "punnet",
    "loaf",
    "slice",
    "g",
    "kg",
    "oz",
    "pound",
    "ml",
    "litre",
    "fl oz",
    "pint",
    "gallon",
    "tsp",
    "tbsp",
    "cup",
    "cm",
    "m");

DELETE FROM tags WHERE name IN (
    "tesco",
    "aldi",
    "b&q",
    "boots",
    "produce",
    "fruits",
    "dairy",
    "bakery",
    "meat & fish",
    "frozen",
    "drinks",
    "pantry",
    "baking",
    "snacks",
    "cleaning",
    "toiletries",
    "household",
    "diy",
    "party",
    "urgent",
    "treat");
